services:
  api:
    build:
      context: ../server/
      dockerfile: ../docker/server/Dockerfile
    container_name: mynotes-api
    ports:
      - "8000:8000"
    environment:
      MYNOTES_ROOT_DIR: /data
    volumes:
      - ./mynotes:/data
    restart: unless-stopped